name: bio_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.1
  encrypt: ^5.0.3
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  flutterfire_cli: ^1.0.0
  integration_test:
    sdk: flutter
  local_auth: ^2.3.0
  mockito: ^5.4.5
  path: ^1.9.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  torch_light: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  